# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mailbox}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joel Friedman", "Patrick Farley"]
  s.date = %q{2009-10-18}
  s.description = %q{Mailbox is a JRuby module that simplifies concurrency and is backed by JVM threads.}
  s.email = %q{asher.friedman@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION.yml",
     "lib/mailbox.rb",
     "mailbox.gemspec",
     "test/mailbox_test.rb"
  ]
  s.homepage = %q{http://joelash.github.com/mailbox}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{mailbox}
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Mailbox is a JRuby module that simplifies concurrency and is backed by JVM threads.}
  s.test_files = [
    "test/mailbox_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jretlang>, [">= 0"])
    else
      s.add_dependency(%q<jretlang>, [">= 0"])
    end
  else
    s.add_dependency(%q<jretlang>, [">= 0"])
  end
end
